### ISSUE TITLE
Wrong Skills

### ISSUE THREAD

**Issue by GlitchMC** [aturfah/eou-grimoire-editor#8]
Ice Breath and Knockdown pull the wrong versions of the skill. They each have two versions, and the first instances of them should be pulled, but they are pulling the 2nd instance.

Knockdown pulls a version that hits a row and binds arms from ID737, instead of the base attack that is just damage from lD483 (referencing the not-official IDson our player skill sheet).

Ice Breath is pulling from ID640 which has varying TP costs, and different stats altogether, instead of the one from ID480.

**Comment by GlitchMC** [comment]
Additionally ,Bloodlust is pulling from the actual attack skill instead of the passive one (pulling 296 instead of 276)

**Comment by GlitchMC** [comment]
Slantwise Cut is pulling Ren's version of the skill

**Comment by aturfah** [comment]
Thank you for this information, I'll correct these mappings in the file.

**Comment by GlitchMC** [comment]
so far my assumption (and experience) has been that all of the skills that have two parts/variants are pulling the wrong one, since the "wrong" ones are always later in the list than the "correct" one, leading me to believe that it's searching in reverse, so searching the other way should solve this

i tried editing the text file myself to try and get it to work right bc im too lazy to read the code lol, but it didn't like that at all >->

**Comment by aturfah** [comment]
That is probably the case, from ones I've tried Boost Up is not pulling the correct one.

**Comment by aturfah** [comment]
Should be addressed in [latest release](https://github.com/aturfah/eou-grimoire-editor/releases/tag/V2.0.0).

Will wait for confirmation from @GlitchMC before closing

**Comment by GlitchMC** [comment]
Everything seems to be working correctly with the skills i've checked
