### ISSUE TITLE
Tab for entering skills

### ISSUE THREAD

**Issue by GlitchMC** [aturfah/eou-grimoire-editor#9]
Would it be possible to allow the use of Tab to confirm a skill edit?

As of now, Enter or Return is required to submit an update in the program, which means having to either tab 15 times back to where you were, or click.
The first time i was using the program i was writing skill names and tabbing to the next line assuming it would work and then found out it wasn't and couldn't think of why until i read that only Enter and Return make a submission.

**Comment by aturfah** [comment]
See comment on #10, this will not be an issue once the UI is switched to a web-based interface.

**Comment by aturfah** [comment]
Addressed in #12
